INSERT INTO STUDENT (Id, FirstName, LastName, Email, Mobile,Age) 
	VALUES (SELECT NEWID(),'Debra','Burks','Debra.Burks@anywhere.com',91254684566,20)
INSERT INTO STUDENT (Id, FirstName, LastName, Email, Mobile,Age) 
	VALUES (SELECT NEWID(),'Kasha','Todd','Kasha.Todd@anywhere.com',91254684576,30)
INSERT INTO STUDENT (Id, FirstName, LastName, Email, Mobile,Age) 
	VALUES (SELECT NEWID(),'Tameka','Fisher','Tameka.Fisher@anywhere.com',91254684586,40)
INSERT INTO STUDENT (Id, FirstName, LastName, Email, Mobile,Age) 
	VALUES (SELECT NEWID(),'Daryl','Spence','Daryl.Spence@anywhere.com',91254684596,50)
INSERT INTO STUDENT (Id, FirstName, LastName, Email, Mobile,Age) 
	VALUES (SELECT NEWID(),'Charolette','Rice','Charolette.Rice@anywhere.com',91254684606,60)

